name = "pd_density"
uuid = "8c582660-71eb-43f7-b5a3-faff279df77c"
authors = ["jona125 <36974316+jona125@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
